apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml

commonLabels:
  app: universal-platform
  managed-by: kustomize

configMapGenerator:
  - name: app-config
    literals:
      - LOG_LEVEL=INFO
      - METRICS_ENABLED=true
      - TRACING_ENABLED=true

secretGenerator:
  - name: app-secrets
    literals:
      - DATABASE_URL=changeme
      - API_KEY=changeme

replicas:
  - name: app-deployment
    count: 2

images:
  - name: app-image
    newName: gcr.io/PROJECT_ID/app
    newTag: latest

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app-deployment
    spec:
      template:
        spec:
          containers:
          - name: app
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"

vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      name: app-service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name

configurations:
  - kustomizeconfig.yaml