version: 2
updates:
  # Python dependencies (Poetry)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    reviewers:
      - "jhousteau"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    ignore:
      # Ignore major version updates for core dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
    target-branch: "main"
    open-pull-requests-limit: 5
    reviewers:
      - "jhousteau"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    target-branch: "main"
    open-pull-requests-limit: 3
    reviewers:
      - "jhousteau"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Pre-commit hooks
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:30"
    target-branch: "main"
    open-pull-requests-limit: 2
    reviewers:
      - "jhousteau"
    labels:
      - "dependencies"
      - "pre-commit"
    commit-message:
      prefix: "pre-commit"
      include: "scope"
    # Only update pre-commit hook versions
    allow:
      - dependency-type: "all"
