# Application SLO/SLA Monitoring Rules
# Defines service level objectives and error budget tracking

groups:
  - name: application_slos
    interval: 30s
    rules:
      # HTTP Request Success Rate SLO (99.9% over 30 days)
      - record: slo:http_request_success_rate:30d
        expr: |
          (
            sum(rate(http_requests_total{code!~"5.."}[30d])) by (service, environment)
            /
            sum(rate(http_requests_total[30d])) by (service, environment)
          ) * 100

      # HTTP Request Latency SLO (95% of requests < 200ms)
      - record: slo:http_request_latency:95percentile:30d
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_seconds_bucket[30d])) by (service, environment, le)
          ) * 1000

      # Error Budget Burn Rate (how fast we're consuming error budget)
      - record: slo:error_budget_burn_rate:1h
        expr: |
          (
            1 - (
              sum(rate(http_requests_total{code!~"5.."}[1h])) by (service, environment)
              /
              sum(rate(http_requests_total[1h])) by (service, environment)
            )
          ) * 100 / 0.1  # 0.1% error budget (99.9% SLO)

      # Database Query Performance SLO
      - record: slo:db_query_success_rate:30d
        expr: |
          (
            sum(rate(db_queries_total{status="success"}[30d])) by (service, environment, database)
            /
            sum(rate(db_queries_total[30d])) by (service, environment, database)
          ) * 100

      - record: slo:db_query_latency:95percentile:30d
        expr: |
          histogram_quantile(0.95,
            sum(rate(db_query_duration_seconds_bucket[30d])) by (service, environment, database, le)
          ) * 1000

      # API Gateway SLO
      - record: slo:api_gateway_success_rate:30d
        expr: |
          (
            sum(rate(api_gateway_requests_total{code!~"5.."}[30d])) by (gateway, environment)
            /
            sum(rate(api_gateway_requests_total[30d])) by (gateway, environment)
          ) * 100

      # Cache Hit Rate SLO (95% hit rate)
      - record: slo:cache_hit_rate:30d
        expr: |
          (
            sum(rate(cache_operations_total{operation="hit"}[30d])) by (service, environment, cache_type)
            /
            sum(rate(cache_operations_total[30d])) by (service, environment, cache_type)
          ) * 100

      # Background Job Success Rate SLO
      - record: slo:background_job_success_rate:30d
        expr: |
          (
            sum(rate(background_jobs_total{status="completed"}[30d])) by (service, environment, job_type)
            /
            sum(rate(background_jobs_total[30d])) by (service, environment, job_type)
          ) * 100

      # External API Dependency SLO
      - record: slo:external_api_success_rate:30d
        expr: |
          (
            sum(rate(external_api_requests_total{code!~"5.."}[30d])) by (service, environment, external_service)
            /
            sum(rate(external_api_requests_total[30d])) by (service, environment, external_service)
          ) * 100

  - name: infrastructure_slos
    interval: 30s
    rules:
      # CPU Utilization SLO (average < 80%)
      - record: slo:cpu_utilization:avg:30d
        expr: |
          100 - (avg by (instance, environment) (irate(node_cpu_seconds_total{mode="idle"}[30d])) * 100)

      # Memory Utilization SLO (average < 85%)
      - record: slo:memory_utilization:avg:30d
        expr: |
          (
            (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance, environment)
            /
            node_memory_MemTotal_bytes by (instance, environment)
          ) * 100

      # Disk Utilization SLO (< 90% full)
      - record: slo:disk_utilization:max:30d
        expr: |
          (
            (node_filesystem_size_bytes - node_filesystem_free_bytes) by (instance, environment, mountpoint)
            /
            node_filesystem_size_bytes by (instance, environment, mountpoint)
          ) * 100

      # Network Error Rate SLO (< 0.1% packet loss)
      - record: slo:network_error_rate:30d
        expr: |
          (
            rate(node_network_transmit_errs_total[30d]) by (instance, environment, device)
            +
            rate(node_network_receive_errs_total[30d]) by (instance, environment, device)
          ) /
          (
            rate(node_network_transmit_packets_total[30d]) by (instance, environment, device)
            +
            rate(node_network_receive_packets_total[30d]) by (instance, environment, device)
          ) * 100

  - name: business_slos
    interval: 60s
    rules:
      # User Registration Success Rate SLO
      - record: slo:user_registration_success_rate:30d
        expr: |
          (
            sum(rate(user_registrations_total{status="success"}[30d])) by (environment)
            /
            sum(rate(user_registrations_total[30d])) by (environment)
          ) * 100

      # Payment Processing Success Rate SLO
      - record: slo:payment_success_rate:30d
        expr: |
          (
            sum(rate(payments_total{status="success"}[30d])) by (environment, payment_method)
            /
            sum(rate(payments_total[30d])) by (environment, payment_method)
          ) * 100

      # Customer Support Ticket Resolution Time SLO
      - record: slo:support_ticket_resolution_time:95percentile:30d
        expr: |
          histogram_quantile(0.95,
            sum(rate(support_ticket_resolution_duration_seconds_bucket[30d])) by (environment, priority, le)
          ) / 3600  # Convert to hours