# Infrastructure SLOs and Recording Rules
# These rules define SLI calculations and SLO thresholds for infrastructure components

groups:
  - name: infrastructure_slis
    interval: 30s
    rules:
      # === CPU UTILIZATION SLIs ===
      - record: infrastructure:cpu_utilization:rate5m
        expr: |
          (
            (1 - rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100
          )
        labels:
          sli_type: "performance"
          component: "compute"

      - record: infrastructure:cpu_utilization:p95_5m
        expr: |
          histogram_quantile(0.95,
            rate(node_cpu_seconds_total[5m])
          )
        labels:
          sli_type: "performance"
          component: "compute"

      # === MEMORY UTILIZATION SLIs ===
      - record: infrastructure:memory_utilization:rate5m
        expr: |
          (
            (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) /
            node_memory_MemTotal_bytes
          ) * 100
        labels:
          sli_type: "performance"
          component: "memory"

      # === DISK UTILIZATION SLIs ===
      - record: infrastructure:disk_utilization:rate5m
        expr: |
          (
            (node_filesystem_size_bytes - node_filesystem_avail_bytes) /
            node_filesystem_size_bytes
          ) * 100
        labels:
          sli_type: "performance"
          component: "storage"

      - record: infrastructure:disk_iops:rate5m
        expr: |
          rate(node_disk_reads_completed_total[5m]) +
          rate(node_disk_writes_completed_total[5m])
        labels:
          sli_type: "performance"
          component: "storage"

      # === NETWORK SLIs ===
      - record: infrastructure:network_throughput_bytes:rate5m
        expr: |
          rate(node_network_receive_bytes_total[5m]) +
          rate(node_network_transmit_bytes_total[5m])
        labels:
          sli_type: "performance"
          component: "network"

      - record: infrastructure:network_errors:rate5m
        expr: |
          rate(node_network_receive_errs_total[5m]) +
          rate(node_network_transmit_errs_total[5m])
        labels:
          sli_type: "availability"
          component: "network"

      # === LOAD AVERAGE SLIs ===
      - record: infrastructure:load_average:rate5m
        expr: |
          node_load1 / scalar(count(count(node_cpu_seconds_total) by (cpu)))
        labels:
          sli_type: "performance"
          component: "compute"

  - name: infrastructure_slos
    interval: 30s
    rules:
      # === CPU AVAILABILITY SLO ===
      # Target: 95% of time CPU utilization < 80%
      - record: infrastructure:slo_cpu_availability:ratio_rate5m
        expr: |
          (
            sum(rate(infrastructure:cpu_utilization:rate5m < 80[5m])) /
            sum(rate(infrastructure:cpu_utilization:rate5m[5m]))
          )
        labels:
          slo_type: "availability"
          slo_target: "0.95"
          component: "compute"

      # === MEMORY AVAILABILITY SLO ===
      # Target: 99% of time memory utilization < 85%
      - record: infrastructure:slo_memory_availability:ratio_rate5m
        expr: |
          (
            sum(rate(infrastructure:memory_utilization:rate5m < 85[5m])) /
            sum(rate(infrastructure:memory_utilization:rate5m[5m]))
          )
        labels:
          slo_type: "availability"
          slo_target: "0.99"
          component: "memory"

      # === DISK AVAILABILITY SLO ===
      # Target: 99.9% of time disk utilization < 90%
      - record: infrastructure:slo_disk_availability:ratio_rate5m
        expr: |
          (
            sum(rate(infrastructure:disk_utilization:rate5m < 90[5m])) /
            sum(rate(infrastructure:disk_utilization:rate5m[5m]))
          )
        labels:
          slo_type: "availability"
          slo_target: "0.999"
          component: "storage"

      # === NETWORK ERROR RATE SLO ===
      # Target: 99.9% of packets without errors
      - record: infrastructure:slo_network_reliability:ratio_rate5m
        expr: |
          1 - (
            sum(rate(infrastructure:network_errors:rate5m[5m])) /
            sum(rate(node_network_receive_packets_total[5m]) +
                rate(node_network_transmit_packets_total[5m]))
          )
        labels:
          slo_type: "reliability"
          slo_target: "0.999"
          component: "network"

  - name: infrastructure_slo_alerts
    rules:
      # === SLO BURN RATE ALERTS ===
      
      # Fast burn rate: 2% error budget in 1 hour (14.4x burn rate)
      - alert: InfrastructureSLOFastBurn
        expr: |
          (
            infrastructure:slo_cpu_availability:ratio_rate5m < 0.856 or
            infrastructure:slo_memory_availability:ratio_rate5m < 0.856 or
            infrastructure:slo_disk_availability:ratio_rate5m < 0.856 or
            infrastructure:slo_network_reliability:ratio_rate5m < 0.856
          )
        for: 2m
        labels:
          severity: critical
          alert_type: slo_burn_rate
          burn_rate: fast
        annotations:
          summary: "Infrastructure SLO fast burn rate detected"
          description: |
            The infrastructure SLO is consuming error budget at {{ $value }}x the normal rate.
            At this rate, the entire error budget will be exhausted in less than 1 hour.
            Component: {{ $labels.component }}
            Current SLO: {{ $value }}
            Target SLO: {{ $labels.slo_target }}

      # Medium burn rate: 5% error budget in 6 hours (6x burn rate)
      - alert: InfrastructureSLOMediumBurn
        expr: |
          (
            infrastructure:slo_cpu_availability:ratio_rate5m < 0.7 or
            infrastructure:slo_memory_availability:ratio_rate5m < 0.7 or
            infrastructure:slo_disk_availability:ratio_rate5m < 0.7 or
            infrastructure:slo_network_reliability:ratio_rate5m < 0.7
          )
        for: 15m
        labels:
          severity: warning
          alert_type: slo_burn_rate
          burn_rate: medium
        annotations:
          summary: "Infrastructure SLO medium burn rate detected"
          description: |
            The infrastructure SLO is consuming error budget at {{ $value }}x the normal rate.
            Component: {{ $labels.component }}
            Current SLO: {{ $value }}
            Target SLO: {{ $labels.slo_target }}

      # Slow burn rate: 10% error budget in 3 days (2x burn rate)
      - alert: InfrastructureSLOSlowBurn
        expr: |
          (
            infrastructure:slo_cpu_availability:ratio_rate5m < 0.9 or
            infrastructure:slo_memory_availability:ratio_rate5m < 0.9 or
            infrastructure:slo_disk_availability:ratio_rate5m < 0.9 or
            infrastructure:slo_network_reliability:ratio_rate5m < 0.9
          )
        for: 1h
        labels:
          severity: info
          alert_type: slo_burn_rate
          burn_rate: slow
        annotations:
          summary: "Infrastructure SLO slow burn rate detected"
          description: |
            The infrastructure SLO is consuming error budget at a sustained rate.
            Component: {{ $labels.component }}
            Current SLO: {{ $value }}
            Target SLO: {{ $labels.slo_target }}

  - name: infrastructure_capacity_alerts
    rules:
      # === CAPACITY PLANNING ALERTS ===
      - alert: HighCPUUtilization
        expr: infrastructure:cpu_utilization:rate5m > 80
        for: 5m
        labels:
          severity: warning
          alert_type: capacity
          component: compute
        annotations:
          summary: "High CPU utilization on {{ $labels.instance }}"
          description: |
            CPU utilization is {{ $value }}% on instance {{ $labels.instance }}.
            Consider scaling up or optimizing workloads.

      - alert: CriticalCPUUtilization
        expr: infrastructure:cpu_utilization:rate5m > 95
        for: 2m
        labels:
          severity: critical
          alert_type: capacity
          component: compute
        annotations:
          summary: "Critical CPU utilization on {{ $labels.instance }}"
          description: |
            CPU utilization is {{ $value }}% on instance {{ $labels.instance }}.
            Immediate action required.

      - alert: HighMemoryUtilization
        expr: infrastructure:memory_utilization:rate5m > 85
        for: 5m
        labels:
          severity: warning
          alert_type: capacity
          component: memory
        annotations:
          summary: "High memory utilization on {{ $labels.instance }}"
          description: |
            Memory utilization is {{ $value }}% on instance {{ $labels.instance }}.

      - alert: CriticalMemoryUtilization
        expr: infrastructure:memory_utilization:rate5m > 95
        for: 2m
        labels:
          severity: critical
          alert_type: capacity
          component: memory
        annotations:
          summary: "Critical memory utilization on {{ $labels.instance }}"
          description: |
            Memory utilization is {{ $value }}% on instance {{ $labels.instance }}.
            Risk of OOM conditions.

      - alert: HighDiskUtilization
        expr: infrastructure:disk_utilization:rate5m > 85
        for: 10m
        labels:
          severity: warning
          alert_type: capacity
          component: storage
        annotations:
          summary: "High disk utilization on {{ $labels.instance }}"
          description: |
            Disk utilization is {{ $value }}% on {{ $labels.device }} 
            ({{ $labels.mountpoint }}) on instance {{ $labels.instance }}.

      - alert: CriticalDiskUtilization
        expr: infrastructure:disk_utilization:rate5m > 95
        for: 5m
        labels:
          severity: critical
          alert_type: capacity
          component: storage
        annotations:
          summary: "Critical disk utilization on {{ $labels.instance }}"
          description: |
            Disk utilization is {{ $value }}% on {{ $labels.device }} 
            ({{ $labels.mountpoint }}) on instance {{ $labels.instance }}.
            Risk of disk full conditions.

      - alert: HighNetworkErrors
        expr: infrastructure:network_errors:rate5m > 100
        for: 5m
        labels:
          severity: warning
          alert_type: reliability
          component: network
        annotations:
          summary: "High network error rate on {{ $labels.instance }}"
          description: |
            Network error rate is {{ $value }} errors/sec on 
            interface {{ $labels.device }} on instance {{ $labels.instance }}.

      - alert: NodeDown
        expr: up{job="node-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          alert_type: availability
          component: node
        annotations:
          summary: "Node {{ $labels.instance }} is down"
          description: |
            Node {{ $labels.instance }} has been down for more than 1 minute.

  - name: infrastructure_performance_alerts
    rules:
      # === PERFORMANCE ALERTS ===
      - alert: HighLoadAverage
        expr: infrastructure:load_average:rate5m > 2
        for: 5m
        labels:
          severity: warning
          alert_type: performance
          component: compute
        annotations:
          summary: "High load average on {{ $labels.instance }}"
          description: |
            Load average per CPU core is {{ $value }} on instance {{ $labels.instance }}.
            This indicates potential CPU contention.

      - alert: CriticalLoadAverage
        expr: infrastructure:load_average:rate5m > 5
        for: 2m
        labels:
          severity: critical
          alert_type: performance
          component: compute
        annotations:
          summary: "Critical load average on {{ $labels.instance }}"
          description: |
            Load average per CPU core is {{ $value }} on instance {{ $labels.instance }}.
            System may be severely overloaded.

      - alert: HighDiskIOPS
        expr: infrastructure:disk_iops:rate5m > 1000
        for: 10m
        labels:
          severity: warning
          alert_type: performance
          component: storage
        annotations:
          summary: "High disk IOPS on {{ $labels.instance }}"
          description: |
            Disk IOPS is {{ $value }} ops/sec on {{ $labels.device }} 
            on instance {{ $labels.instance }}.

      - alert: HighNetworkThroughput
        expr: infrastructure:network_throughput_bytes:rate5m > 100000000  # 100MB/s
        for: 10m
        labels:
          severity: warning
          alert_type: performance
          component: network
        annotations:
          summary: "High network throughput on {{ $labels.instance }}"
          description: |
            Network throughput is {{ $value | humanize1024 }}B/s on 
            interface {{ $labels.device }} on instance {{ $labels.instance }}.