# Universal Project Platform - Governance Configuration
# This file defines the comprehensive governance framework for all projects

governance:
  version: "1.0.0"
  organization: "whitehorse"
  enforcement_level: "strict"  # strict, moderate, advisory

  # Global settings
  settings:
    default_region: "us-central1"
    audit_retention_days: 2555  # 7 years
    compliance_scan_frequency: "daily"
    cost_review_frequency: "weekly"
    security_scan_frequency: "continuous"

  # Policy enforcement
  policies:
    organization_policies: true
    naming_conventions: true
    resource_constraints: true
    security_baseline: true
    cost_controls: true

  # Compliance frameworks
  compliance:
    enabled_frameworks:
      - soc2
      - gdpr
      - iso27001
    auto_remediation: true
    continuous_monitoring: true
    evidence_collection: true

  # Audit settings
  auditing:
    comprehensive_logging: true
    change_approval_workflow: true
    access_pattern_analysis: true
    automated_reporting: true
    immutable_logs: true

  # Cost management
  cost_control:
    budget_enforcement: true
    quota_management: true
    spending_alerts: true
    optimization_recommendations: true
    cost_allocation: true

  # Security scanning
  security_scanning:
    infrastructure_scans: true
    code_analysis: true
    container_scanning: true
    dependency_checks: true
    continuous_monitoring: true

  # Reporting
  reporting:
    executive_dashboards: true
    operational_metrics: true
    compliance_reports: true
    cost_analytics: true
    security_metrics: true

# Environment-specific overrides
environments:
  dev:
    enforcement_level: "moderate"
    approval_required: false

  staging:
    enforcement_level: "strict"
    approval_required: true

  prod:
    enforcement_level: "strict"
    approval_required: true
    multi_approval_required: true

# Integration settings
integrations:
  terraform: true
  gcp_organization_policies: true
  aws_service_control_policies: true
  azure_policy_definitions: true
  kubernetes_policies: true

# Notification settings
notifications:
  slack:
    enabled: true
    channels:
      compliance: "#compliance-alerts"
      security: "#security-alerts"
      cost: "#cost-alerts"

  email:
    enabled: true
    recipients:
      compliance_team: ["compliance@whitehorse.ai"]
      security_team: ["security@whitehorse.ai"]
      finance_team: ["finance@whitehorse.ai"]

  pagerduty:
    enabled: true
    critical_alerts: true
