# MCP Development Configuration Template
# Optimized configuration for development and testing environments

# MCP Server Configuration
mcp:
  server:
    # Network configuration
    host: "127.0.0.1"  # Local development only
    port: 8080

    # Protocol support
    enableAuth: false    # Disabled for easier development
    enableWebSocket: true
    enableHttp: true

    # CORS - permissive for development
    corsOrigins: ["*"]

    # Connection limits - reduced for development
    maxConnections: 100
    maxRequestsPerConnection: 100

    # Shorter timeouts for faster feedback
    requestTimeout: 10000     # 10 seconds
    keepAliveTimeout: 2000    # 2 seconds
    websocketTimeout: 60000   # 1 minute

    # Request size limits
    maxRequestSize: "1MB"
    maxPayloadSize: "5MB"

  # Authentication - Disabled for development
  auth:
    enabled: false

  # Monitoring - Basic monitoring for development
  monitoring:
    enabled: true
    metricsPort: 8081

    # Frequent health checks for development
    healthCheckInterval: 10  # seconds
    healthCheckTimeout: 5    # seconds

    # Metrics collection
    metricsInterval: 10      # seconds
    metricsRetention: 3600   # 1 hour

    # Tracing disabled for development simplicity
    tracing:
      enabled: false

    # Simple console logging
    logging:
      level: "debug"
      format: "pretty"  # Human-readable format
      destination: "console"
      includeStackTrace: true

  # Service Registry - Simplified
  services:
    registry:
      maxServices: 50
      healthCheckInterval: 15  # seconds
      cleanupInterval: 60      # 1 minute
      serviceTimeout: 30       # seconds

    # Load balancing disabled for development
    loadBalancer:
      enabled: false

  # Security - Minimal for development
  security:
    # No rate limiting for development
    rateLimiting:
      enabled: false

    # Basic request validation
    requestValidation:
      enabled: true
      maxRequestSize: "1MB"
      validateHeaders: false
      validatePayload: true
      sanitizeInput: false

    # No security headers for development
    securityHeaders:
      enabled: false

# Claude-Talk Integration - Development Mode
claude_talk:
  integration:
    enabled: true
    mock_mode: true  # Use mock responses for faster development

    # Shorter timeouts for development
    session_timeout: 300     # 5 minutes
    max_concurrent_agents: 10
    agent_startup_timeout: 15  # seconds

    # Message handling
    message_buffer_size: 100
    message_timeout: 60      # 1 minute
    streaming_enabled: true

  # Resource Management - Minimal for development
  resources:
    defaults:
      memory: "512MB"
      cpu: "250m"       # 0.25 CPU core
      storage: "256MB"
      timeout: 300      # 5 minutes

    limits:
      memory: "2GB"
      cpu: "1000m"      # 1 CPU core
      storage: "1GB"
      timeout: 1800     # 30 minutes

  # Agent Configuration - Development
  agents:
    supported_types:
      - "claude-3.5-sonnet"
      - "mock-agent"  # Mock agent for testing

    lifecycle:
      max_idle_time: 60      # 1 minute
      cleanup_interval: 120  # 2 minutes
      graceful_shutdown_timeout: 10  # seconds

# External Services - Development Mode
external_services:
  # GCP Integration - Disabled or mocked
  gcp:
    enabled: false  # Use local development instead

  # Kubernetes - Not used in development
  kubernetes:
    enabled: false

# Development-Specific Features
development:
  # Hot reload support
  hot_reload:
    enabled: true
    watch_paths: ["./src", "./config"]
    debounce_delay: 1000  # 1 second

  # Development tools
  dev_tools:
    enabled: true
    debug_endpoints: true
    mock_services: true
    test_harness: true

  # Auto-generated test data
  test_data:
    enabled: true
    generate_mock_agents: true
    generate_sample_requests: true

  # Development metrics
  dev_metrics:
    enabled: true
    detailed_timing: true
    memory_profiling: true
    request_logging: true

# Feature Flags - Development Profile
features:
  experimental:
    advanced_routing: true     # Enable for testing
    ml_based_load_balancing: false
    edge_caching: false

  beta:
    websocket_compression: true
    request_deduplication: false  # Disabled to avoid confusion
    circuit_breaker_ml: false

  stable:
    health_checks: true
    service_discovery: true
    load_balancing: false  # Simplified for development
    rate_limiting: false   # Disabled for development
    monitoring: true
    authentication: false # Disabled for development

# Simplified Alerting for Development
alerting:
  enabled: false  # Typically not needed in development

# No Backup in Development
backup:
  enabled: false

# Development Performance Settings
performance:
  memory:
    gc_target_percentage: 50  # More aggressive GC for development
    max_heap_size: "1GB"

  connections:
    keep_alive: false  # Simpler connection handling
    tcp_no_delay: true
    socket_reuse: false

  threading:
    worker_threads: 2  # Fixed small number for development
    io_threads: 2

  caching:
    enabled: false  # Disable caching to see fresh data

# Minimal Compliance for Development
compliance:
  data_governance:
    enabled: false

  audit_logging:
    enabled: false

  privacy:
    pii_detection: false
    pii_masking: false

# Development Metadata
metadata:
  version: "1.0.0-dev"
  config_version: "2024-01-01"
  environment: "development"

# Test Configuration
testing:
  # Unit test settings
  unit_tests:
    mock_external_services: true
    use_in_memory_database: true
    parallel_execution: true

  # Integration test settings
  integration_tests:
    test_timeout: 30  # seconds
    cleanup_after_test: true
    isolated_test_environment: true

  # Load test settings
  load_tests:
    max_concurrent_users: 10
    test_duration: 60  # seconds
    ramp_up_time: 10   # seconds

# Mock Services Configuration
mocks:
  claude_api:
    enabled: true
    response_delay: 100  # milliseconds
    success_rate: 95     # percent

  external_services:
    enabled: true
    mock_responses_file: "./mocks/responses.json"

# Development Utilities
utils:
  # Database utilities
  database:
    auto_migrate: true
    seed_test_data: true
    reset_on_restart: false

  # Service utilities
  services:
    auto_register_local_services: true
    discover_services_on_startup: true

  # Debugging utilities
  debug:
    enable_debug_endpoints: true
    log_all_requests: false  # Can be noisy
    log_all_responses: false
    capture_request_timing: true

schema_version: "1.0.0"
