# Production Environment Configuration
# Overrides for production deployment

system:
  environment: "production"
  debug: false
  log_level: "WARN"
  base_url: "https://api.bootstrapper.dev"

  features:
    # More conservative feature flags for production
    automated_optimization: false  # Require manual approval
    self_healing: true
    cross_project_analysis: true
    predictive_analytics: true

intelligence:
  auto_fix:
    auto_execute: false  # Always require approval in production
    timeout: 600  # Longer timeout for production
    concurrent_fixes: 1  # Conservative concurrency

    # More restrictive categories
    categories:
      security: false  # Require manual security fixes
      dependencies: false  # Manual dependency updates
      configuration: true
      infrastructure: false

    notifications:
      on_execution: true
      on_completion: true
      on_failure: true

  optimization:
    analysis_interval: 7200  # Every 2 hours
    cost_threshold: 500  # Higher threshold for production
    auto_apply_threshold: 0  # No auto-apply in production

  predictions:
    confidence_threshold: 0.8  # Higher confidence required

    alerts:
      high_confidence: 0.90
      critical_prediction: 0.95

  self_healing:
    monitoring_interval: 30  # More frequent monitoring
    auto_heal_enabled: true
    max_healing_attempts: 2  # Conservative healing attempts

    # Restricted healing actions
    actions:
      restart_services: true
      clean_disk_space: true
      optimize_memory: false  # Too risky for production
      fix_permissions: false  # Require manual intervention
      update_dependencies: false

coordination:
  coordination_interval: 60  # Less frequent coordination
  health_check_interval: 30  # More frequent health checks
  max_concurrent_tasks: 3  # Conservative concurrency
  task_timeout: 600  # Longer timeout
  auto_resolve_conflicts: false  # Manual conflict resolution

deployment:
  default_strategy: "blue_green"  # Safest strategy for production

  strategies:
    blue_green:
      timeout: 3600  # 1 hour for production deployments
      health_check_interval: 15
    canary:
      initial_percentage: 5  # More conservative canary
      increment_percentage: 15
      timeout: 7200  # 2 hours
    rolling:
      max_unavailable: 0  # Zero downtime requirement
      timeout: 3600

  validation:
    pre_deploy_checks: true
    post_deploy_validation: true
    rollback_on_failure: true

  approvals:
    production_required: true
    staging_required: true
    development_required: false

governance:
  compliance_enabled: true
  policy_enforcement: "strict"
  audit_logging: true
  cost_monitoring: true

  frameworks:
    soc2: true
    gdpr: true
    iso27001: true

  cost_control:
    budget_alerts: true
    spend_limits: true
    optimization_recommendations: true

security:
  authentication_required: true
  authorization_enabled: true
  encryption_at_rest: true
  encryption_in_transit: true
  vulnerability_scanning: true

  sessions:
    timeout: 1800  # 30 minutes for production
    refresh_enabled: true
    secure_cookies: true

  api:
    rate_limiting: true
    cors_enabled: false  # Restrictive CORS
    csrf_protection: true

monitoring:
  retention_days: 90  # Longer retention for production

  metrics:
    collection_interval: 30  # More frequent collection
    batch_size: 200
    compression_enabled: true

  logging:
    level: "WARN"  # Less verbose logging
    structured: true
    format: "json"

  tracing:
    sampling_rate: 0.05  # 5% sampling to reduce overhead
    max_span_duration: 7200

  alerting:
    error_rate_threshold: 0.01  # 1% - stricter in production
    latency_threshold: 500  # 500ms - tighter SLA
    availability_threshold: 0.999  # 99.9% availability

performance:
  cache:
    default_ttl: 7200  # 2 hours
    max_size: "10GB"  # Larger cache for production
    compression: true

  database:
    connection_pool_size: 50  # Larger pool for production
    query_timeout: 10  # Stricter timeout
    slow_query_threshold: 500  # More aggressive slow query detection

  network:
    keepalive_enabled: true
    compression_enabled: true
    timeout: 10  # Stricter network timeout

integrations:
  github:
    enabled: true

  slack:
    enabled: true

  pagerduty:
    enabled: true

  gcp:
    enabled: true

development:
  debug_mode: false
  hot_reload: false
  mock_external_services: false
  test_data_enabled: false

  testing:
    integration_tests: false
    performance_tests: false
    security_tests: false
    chaos_testing: false
