---
# Service Discovery Configuration for Universal Platform

# Global settings
discovery_interval: 60  # seconds
service_ttl: 300        # seconds
log_level: INFO

# Enabled discovery methods
enabled_methods:
  - kubernetes
  - prometheus
  # - consul
  # - gcp_compute

# Kubernetes discovery configuration
kubernetes:
  in_cluster: true
  namespace: "default"  # or "all" for all namespaces
  label_selectors:
    - "app"
    - "service"
    - "component"
  annotation_mappings:
    "monitoring.universal-platform/team": "team"
    "monitoring.universal-platform/language": "language"
    "monitoring.universal-platform/framework": "framework"
    "monitoring.universal-platform/type": "type"
    "monitoring.universal-platform/metrics-path": "metrics_path"
    "monitoring.universal-platform/health-path": "health_check_path"

# Prometheus discovery configuration
prometheus:
  url: "http://prometheus:9090"
  query_timeout: 30

# Consul discovery configuration (optional)
consul:
  host: "consul"
  port: 8500
  datacenter: "dc1"
  service_tags:
    - "monitoring"
    - "universal-platform"

# GCP Compute discovery configuration (optional)
gcp:
  project_id: ""
  zones:
    - "us-central1-a"
    - "us-central1-b"
    - "us-east1-a"
  instance_filters:
    - "labels.monitoring=enabled"
    - "labels.environment!=test"

# Output configuration
output:
  prometheus_file: "/etc/prometheus/targets/services.json"
  grafana_provisioning: "/etc/grafana/provisioning/datasources/"
  service_registry: "/var/lib/monitoring/services.json"

# Service type inference rules
service_type_rules:
  web_application:
    - "web"
    - "frontend"
    - "ui"
    - "nginx"
  api_service:
    - "api"
    - "backend"
    - "service"
    - "rest"
    - "graphql"
  worker_service:
    - "worker"
    - "job"
    - "processor"
    - "consumer"
    - "task"
  database:
    - "db"
    - "database"
    - "postgres"
    - "mysql"
    - "mongodb"
    - "redis"
  cache:
    - "cache"
    - "redis"
    - "memcached"
  message_queue:
    - "queue"
    - "mq"
    - "rabbitmq"
    - "kafka"
    - "nats"
  load_balancer:
    - "lb"
    - "load-balancer"
    - "nginx"
    - "traefik"
    - "envoy"

# Default service configuration
default_service:
  protocol: "http"
  metrics_path: "/metrics"
  health_check_path: "/health"
  port: 8080

# Filtering rules
filters:
  exclude_namespaces:
    - "kube-system"
    - "kube-public"
    - "istio-system"
  exclude_services:
    - "kubernetes"
    - "prometheus"
    - "grafana"
  include_only_labeled: false
  required_labels: []

# Discovery method priorities (higher number = higher priority)
method_priorities:
  kubernetes: 10
  prometheus: 8
  consul: 6
  gcp_compute: 4
  static_config: 2